language: node_js

services:
  - docker

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

install:
  - npm install

script:
  - npm run build
  - docker build -t $DOCKER_IMAGE .
  - docker run -d -p 127.0.0.1:80:80 $DOCKER_IMAGE
  - docker ps -a 

after_success:
  - docker tag $DOCKER_IMAGE:latest  
  - docker push $DOCKER_IMAGE:latest
  - docker rm -f $DOCKER_IMAGE
