services:
  - docker

script:
  - docker build -t $DOCKER_IMAGE .
  - docker run -d -p 127.0.0.1:80:80 $DOCKER_IMAGE
  - docker ps -a

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker tag $DOCKER_IMAGE:latest && docker push $DOCKER_IMAGE:latest
  on:
    branch: master